### PR TITLE
init support for django4.2

### PR DESCRIPTION
**Pull request by FreemanPancake**
## Related resources

* add support for django 4.2 and python 3.10
* remove support django < 3.2 and python < 3.8

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by joshyu** [comment]
@fsbraun / @Aiky30 ,

please help to review this PR.

**Review by fsbraun — APPROVED** [review]
LGTM! The tests fail, since there are migrations missing in the core for Django 4.2. They are no-ops,  but still show up.

I suggest you add a change to the `tests.test_migrations` test and only check if there are migrations for the djangocms-snippet module:

```
        try:
            call_command("makemigrations", "djangocms_snippet", **options)
        except SystemExit as e:
            status_code = str(e)
        else:
            # the "no changes" exit code is 0
            status_code = "0"
```

**Comment by joshyu** [comment]
@fsbraun ,

do you mean I add a `SkipIf` to check django version. skip if django == 4.2?
as there are no errors under django 3.2

**Comment by fsbraun** [comment]
No, I'm suggesting to change that code snippet in the `tests/tests_migrations.py` file. The difference is the 2nd line.

**Comment by joshyu** [comment]
@fsbraun,

Sorry I didn't understand how to do this. do you mean change `makemigration` to `migrate`?
If my understanding is not correct, please can you tell me how to do it? sorry for the bother.

**Comment by fsbraun** [comment]
Sorry, my mistake. I've looked at the wrong branch (`support/4.0.0` instead of `support/4.0.x`). The proposed change has already been made.

Next, I suggest running the tests locally with the `dry_run` option temporarily set to `False`. This will create a new migration file which should be committed to the PR.

**Comment by joshyu** [comment]
@fsbraun ,
please help to approve the workflow and review the update.

Cheers

**Comment by joshyu** [comment]
@fsbraun , can you check whether the PR is OK? Thanks.

**Pull request merged**
