### PR TITLE
Added site field in models n site filter in admin

### PR DESCRIPTION
**Pull request by vipulnarang95**
## Description

Added site field in Snippet Model
Added site filter in Snippet admin

### CODE REVIEW

**Comment by vipulnarang95** [comment]
@fsbraun Can you please review this?

**Review by marksweb — APPROVED** [review]

**Review by fsbraun — CHANGES_REQUESTED** [review]
@vipulnarang95 Can I suggest a few things to make this fully integrated:

* Only offer snippets in the plugin that belong to either no site (implying no site restriction) or the current site
* Only render snippets if they belong to the current site (or have no site which means available on all sites). The reason to do this is that the site field of a snippet can change over time. I would assume that a site only renders snippets that are "legal" on the site
* Can you add tests for the snippet selection, rendering and upon changing site?

I would like to port forward / (backward?) the changes to the main branch later.

**Comment by vipulnarang95** [comment]
Hi @fsbraun @marksweb 
Can you please review this again. Implemented site support as suggested.

**Comment by vipulnarang95** [comment]
@fsbraun Can you also approve the workflow run please?

**Review by fsbraun — APPROVED** [review]

**Comment by fsbraun** [comment]
LGTM!

**Pull request merged**
